config/routes.rb
Rails.application.routes.draw do
  resources :manufacturers, only: [:index, :new, :create]
  resources :cars, only: [:index, :new, :create]
end

app/models/car.rb
class Car < ActiveRecord::Base
  validates :type, presence: true
  validates :manufacturer, presence: true
  validates :color, presence: true
  validates :year, presence: true, inclusion: { within: 1920..Time.now.year }
  validates :mileage, presence: true

  has_many :manufacturer_car_relationships, dependent: :destroy
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  validates :name, presence: true
  validates :country, presence: true

  has_many :manufacturer_car_relationships, dependent: :destroy
end

app/models/manufacturer_car_relationship.rb
class ManufacturerCarRelationship < ActiveRecord::Base
  validates :manufacturer_id, presence: true
  validates :car_id, presence: true

  belongs_to :manufacturer
  belongs_to :car
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)

    if @car.save
      flash[:notice] = "Success"
      redirect_to cars_path
    else
      flash.now[:notice] = "Error"
      render :new
    end
  end

  private
  def car_params
    params.require(:car).permit(:type, :manufacturer, :color, :year, :mileage, :description)
  end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  def index
    @manufacturers = Manufacturer.all
  end

  def new
    @manufacturer = Manufacturer.new
  end

  def create
    @manufacturer = Manufacturer.new(manufacturer_params)

    if @manufacturer.save
      flash[:notice] = "Success"
      redirect_to manufacturers_path
    else
      flash.now[:notice] = "Error"
      render :new
    end
  end

  private
  def manufacturer_params
    params.require(:manufacturer).permit(:name, :country)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/index.html.erb
<h1>All Cars</h1>

<table border="1" style="width:300px">
  <thead>
    <tr>
      <td>Type</td>
      <td>Manufacturer</td>
      <td>Color</td>
      <td>Year</td>
      <td>Mileage</td>
      <td>Description</td>
    </tr>
  </thead>
  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.type %></td>
        <td><%= car.manufacturer %></td>
        <td><%= car.color %></td>
        <td><%= car.year %></td>
        <td><%= car.mileage %></td>
        <td><%= car.description %></td>
      </tr>
    <% end %>
  </tbody>
</table><br/>
<%= link_to 'Add a New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>Add a Car</h1>

<%= notice %>
<%= alert %>

<%= simple_form_for(@car) do |f| %>
  <%= f.input :type %>
  <%= f.input :manufacturer %>
  <%= f.input :color %>
  <%= f.input :year %>
  <%= f.input :mileage %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Car Listing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="nav-bar">
    <ul class="nav">
      <li id="title">Car Manufacturer Listing</li>
      <div class="list">
        <li><%= link_to 'Manufacturers List', manufacturers_path %></li>
        <li> | </li>
        <li><%= link_to 'Cars List', cars_path %></li>
      </div>
    </ul>
  </div>

<%= yield %>

</body>
</html>

app/views/manufacturers/index.html.erb
<h1>All Manufacturers</h1>

<table border="1" style="width:300px">
  <thead>
    <tr>
      <td>Name</td>
      <td>Country</td>
    </tr>
  </thead>
  <tbody>
    <% @manufacturers.each do |manufacturer| %>
      <tr>
        <td><%= manufacturer.name %></td>
        <td><%= manufacturer.country %></td>
      </tr>
    <% end %>
  </tbody>
</table><br/>
<%= link_to 'Add a New Manufacturer', new_manufacturer_path %>

app/views/manufacturers/new.html.erb
<h1>Add a Manufacturer</h1>

<%= notice %>
<%= alert %>

<%= simple_form_for(@manufacturer) do |f| %>
  <%= f.input :name %>
  <%= f.label :country %>
  <%= f.country_select :country, {priority: %w(US CA), prompt: 'Please select a country'} %>
  <%= f.button :submit %>
<% end %>